development:
  secret_key_base:  asdflkjasdlfkjasldfkj

test:
  secret_key_base:  asdflkhasldfhlhaskdlflakhsdf

production:
  secret_key_base: 523lk5h2lkjlj6nlk4n6lk4
# development:
#   sendgrid_user:  cemal
#   sendgrid_pass:  1qaZXsw2
#   mail:           admin@securelab.com
#   domain:         localhost:3000
